### ISSUE TITLE
how to implement without database

### ISSUE THREAD

**Issue by raafaar** [lordlothar99/strategy-spring-security-acl#28]
hello,
I found this project because I'm interested in using an implementation that isn't database-oriented. I would like to implement it in a more programmatic and object-oriented way.

I'm lost about making this programmatic implementation. Could someone help me?
I've checked the sample, but I haven't figure out how could it be stored, Using a class?, A config file? Is that implementation included in the project?
I hope someone give me a clue or a guide?
thank you in advance

**Comment by lordlothar99** [comment]
hi @raafaar ! your need is exactly the purpose of this project. indeed I may help you to implement programmatic secturity-ACL implementation. Are you familiar with Spring and Spring-security ?
in order to implement your ACL strategy, here what you need:
1. a Spring-based application (with Spring-boot it's even better)
2. a maven based project (so you have to include both the github repository and the artifact `strategy-spring-security-acl-grant`, as described in "Installation" section of the README)
3. for method-execution filter, add Spring-security annotations on the methods `@PreAuthorize("hasPermission(... )")`
4. Add `Acl("myStrategy")` annotation on the object passed in the `hasPermission` invocation set before
5. Create a `GrantEvaluator` class ; this is the class which will be called each time the annotated method will be called
5. Create a `SimpleAclStrategy` Spring bean named "myStrategy", containing the `GrantEvaluator` you just set

If your project is already hosted somewhere public, feel free to send me a link so it would be easier to help you.

**Comment by raafaar** [comment]
hello @lordlothar99, 
Thank you for answering so fast.
I've been using spring-security for a little time, so I'm getting familiar with it. Currently, what is new for me, is Spring-acl.

I've used cancan in rails, but spring-acl seems more complex. Nevertheless, I'm trying to convince my team and my boss to use a permission-based authorization (like in rails) instead of the more common role-based approach.

I'm working on a new spring-boot project. I'm using gradle (instead of maven).
After checking the sample project, I have added an implementation of AbstractGrantEvaluator (like you said in your comment) and installed it in the SimpleAclStrategy. For now, I only have one or two controllers using @PreAuthorize for testing purposes.

My doubt, for now, is about where should I define the permissions for users. I don't know if it will be a configuration file or a class with the roles and their permissions for the objects/classes. 

May be I'm making a wrong assumption; I think it will be just like the default spring-acl, but defining the permissions into a class or configfile instead of database. Am I right abut thinking like this?

Unfortunately, the project cannot be hosted publicly. I think I can publish some snippet of code or a part of a file, but not the full project.

thank you

**Comment by lordlothar99** [comment]
unlike with Spring-ACL (this project is an alternative to Spring-ACL, motivated several reasons detailled in README ; you won't need Spring-ACL in your project, but only Spring-security and strategy-spring-security-acl-grant artifact), nothing has to be persisted in a database. You would have to implement your strategies in subclasses of `AbstractGrantEvaluator`.
Let's take a webshopping application ; there's a `ShoppingCart` class in this application, and `ShoppingCart` has a property `owner`. We want to ensure only the owner can read or write its own cart.
In `ShoppingCartController`, we add `hasPermission(#shoppingCart, 'SAVE')` annotation on `saveShoppingCart(ShoppingCart shoppingCart)` method
Then we add `Acl("shoppingCartStrategy")` on `ShoppingCart` class
Then we create a `ShoppingCartGrantEvaluator` class, and we add it to a `shoppingCartStrategy` Spring bean (with type `SimpleAclStrategy`).

Each time `ShoppingCartController.saveShoppingCart(..)` method will be called, Spring-security will invoke `ShoppingCartGrantEvaluator` before

in `ShoppingCartGrantEvaluator`, we have to implement something like:
```
  public boolean isGranted(Permission permission, Authentication authentication, ShoppingCart shoppingCart) {
      if (!Permission.SAVE.equals(permission)) {
          // all other permissions denied (if any)
          return false;
      }

      // only owner of this shopping cart has access granted
      return authentication.getPrincipal().equals(shoppingCart.getOwner());
  }
```

we don't need a database, but if you prefer to store some information in the database, your grantEvaluator can still  use a repository...

**Comment by raafaar** [comment]
Oh yeah! Now it's clear for me. 
I were wrong thinking this project were (in some way) extending spring-acl. 
Now I see it's easy to set up. The example in your comment helped me to understand.
Now I can make a functional demo. Thank you.
